apiVersion: v1
kind: Service
metadata:
  name: leonespa-service
spec:
  selector:
    app: leonespa # Deve corrispondere ai label del Deployment
  ports:
    - protocol: TCP
      port: 80 # La porta su cui il servizio ascolta
      targetPort: 80 # La porta nel container
  type: LoadBalancer # Permette di ottenere un IP pubblico
